{% set name = "numba-cuda" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: TBC

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numba >=0.59.1

test:
  imports:
    - numba_cuda
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/NVIDIA/numba-cuda
  summary: 'A CUDA target for Numba'
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://nvidia.github.io/numba-cuda
  dev_url: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - gmarkall
